function mainRouter(app, db, io) {

    /////////////////////////////// ACCOUNT ROUTER STARTS ////////////////////////////////

    const employeeRouter = require(__dirname + '/hr_router/employeeRouter.js')
    const supplierRouter = require(__dirname + '/hr_router/supplierRouter.js')
    const designationRouter = require(__dirname + '/hr_router/designationRouter.js')
    const departmentRouter = require(__dirname + '/hr_router/departmentRouter.js')
    const workingPlaceRouter = require(__dirname + '/hr_router/workingPlaceRouter.js')
    const employeeTypeRouter = require(__dirname + '/hr_router/employeeTypeRouter.js')
    const religionRouter = require(__dirname + '/hr_router/religionRouter.js')
    const bloodGroupRouter = require(__dirname + '/hr_router/bloodGroupRouter.js')
    const dutyShiftRouter = require(__dirname + '/hr_router/dutyShiftRouter.js')
    const addressRouter = require(__dirname + '/hr_router/addressRouter.js')
    const addressTypeRouter = require(__dirname + '/hr_router/addressTypeRouter.js')
    const villageRouter = require(__dirname + '/hr_router/villageRouter.js')
    const postOfficeRouter = require(__dirname + '/hr_router/postOfficeRouter.js')
    const policeStationRouter = require(__dirname + '/hr_router/policeStationRouter.js')
    const districtRouter = require(__dirname + '/hr_router/districtRouter.js')
    const refererRouter = require(__dirname + '/hr_router/refererRouter.js')
    const educationRouter = require(__dirname + '/hr_router/educationRouter.js')
    const experienceRouter = require(__dirname + '/hr_router/experienceRouter.js')
    const salaryRouter = require(__dirname + '/hr_router/salaryRouter.js')
    const attendenceRouter = require(__dirname + '/hr_router/attendenceRouter.js')
    const userRouter = require(__dirname + '/hr_router/userRouter.js')
    const leaveTypeRouter = require(__dirname + '/hr_router/leaveTypeRouter.js')
    const leaveRouter = require(__dirname + '/hr_router/leaveRouter.js')
    const holidayRouter = require(__dirname + '/hr_router/holidayRouter.js')
    const adjustmentRouter = require(__dirname + '/hr_router/adjustmentRouter.js')
    const buyerRouter = require(__dirname + '/hr_router/buyerRouter.js')
    const importFileRouter = require(__dirname + '/hr_router/importFileRouter.js')
    const exportFileRouter = require(__dirname + '/hr_router/exportFileRouter.js')
    const bankAccountRouter = require(__dirname + '/hr_router/bankAccountRouter.js')
    const countryRouter = require(__dirname + '/hr_router/countryRouter.js')
    const paymentRouter = require(__dirname + '/hr_router/paymentRouter.js')
    const deductionRouter = require(__dirname + '/hr_router/deductionRouter.js')
    const mailListRouter = require(__dirname + '/hr_router/mailListRouter.js')
    const getControllerRouter = require(__dirname + '/hr_router/getControllerRouter.js')

    employeeRouter.routerInit(app, db)
    supplierRouter.routerInit(app, db)
    designationRouter.routerInit(app, db)
    departmentRouter.routerInit(app, db)
    workingPlaceRouter.routerInit(app, db)
    employeeTypeRouter.routerInit(app, db)
    religionRouter.routerInit(app, db)
    bloodGroupRouter.routerInit(app, db)
    dutyShiftRouter.routerInit(app, db)
    addressRouter.routerInit(app, db)
    addressTypeRouter.routerInit(app, db)
    villageRouter.routerInit(app, db)
    postOfficeRouter.routerInit(app, db)
    policeStationRouter.routerInit(app, db)
    districtRouter.routerInit(app, db)
    refererRouter.routerInit(app, db)
    educationRouter.routerInit(app, db)
    experienceRouter.routerInit(app, db)
    salaryRouter.routerInit(app, db)
    attendenceRouter.routerInit(app, db)
    userRouter.routerInit(app, db)
    leaveTypeRouter.routerInit(app, db)
    leaveRouter.routerInit(app, db)
    holidayRouter.routerInit(app, db)
    adjustmentRouter.routerInit(app, db)
    buyerRouter.routerInit(app, db)
    importFileRouter.routerInit(app, db)
    exportFileRouter.routerInit(app, db)
    bankAccountRouter.routerInit(app, db)
    countryRouter.routerInit(app, db)
    paymentRouter.routerInit(app, db)
    deductionRouter.routerInit(app, db)
    mailListRouter.routerInit(app, db)
    getControllerRouter.routerInit(app, db)

    io.on('connection', function(s) {
        employeeRouter.socketInit(db, s)
        supplierRouter.socketInit(db, s)
        designationRouter.socketInit(db, s)
        departmentRouter.socketInit(db, s)
        workingPlaceRouter.socketInit(db, s)
        employeeTypeRouter.socketInit(db, s)
        religionRouter.socketInit(db, s)
        bloodGroupRouter.socketInit(db, s)
        dutyShiftRouter.socketInit(db, s)
        addressRouter.socketInit(db, s)
        addressTypeRouter.socketInit(db, s)
        villageRouter.socketInit(db, s)
        postOfficeRouter.socketInit(db, s)
        policeStationRouter.socketInit(db, s)
        districtRouter.socketInit(db, s)
        refererRouter.socketInit(db, s)
        educationRouter.socketInit(db, s)
        experienceRouter.socketInit(db, s)
        salaryRouter.socketInit(db, s)
        attendenceRouter.socketInit(db, s)
        userRouter.socketInit(db, s)
        leaveTypeRouter.socketInit(db, s)
        leaveRouter.socketInit(db, s)
        holidayRouter.socketInit(db, s)
        adjustmentRouter.socketInit(db, s)
        buyerRouter.socketInit(db, s)
        importFileRouter.socketInit(db, s)
        exportFileRouter.socketInit(db, s)
        bankAccountRouter.socketInit(db, s)
        countryRouter.socketInit(db, s)
        paymentRouter.socketInit(db, s)
        deductionRouter.socketInit(db, s)
        mailListRouter.socketInit(db, s)
        getControllerRouter.socketInit(db, s)
    })

    /////////////////////////////// ACCOUNT ROUTER ENDS ////////////////////////////////

}

module.exports.mainRouter = mainRouter;